language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - "10"
  - "11"

script:
  - echo "Running tests against $(node -v) ..."
  - yarn test:prod
  - yarn build

jobs:
  include:
    - stage: deploy
      node_js: "11"
      script: echo "Deploying..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn do-release
