name: Release

on:
  push:
    branches:
      - "master"

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setting up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "10.x" # Use the same node.js version as the one Zeit's uses (currently node10.x)

      - name: Checking out repo
        uses: actions/checkout@v1

      - name: Installing packages
        run: yarn install --frozen-lockfile

      - name: Running tests
        run: yarn test:prod

      - name: Building package
        run: yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          branch: master

      - name: Build storybook
        run: yarn build-storybook
      - name: Deploy storybook static to github pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: storybook-static # The folder the action should deploy.
